- name: Setup
  hosts:
    - bootstrap
    - workers
  tasks:
    - name: Write to /etc/hostname
      ansible.builtin.copy:
        content: "{{ hostname }}"
        dest: /etc/hostname
    - name: Write to /etc/hosts
      ansible.builtin.copy:
        content: |
          127.0.0.1 {{ hostname }} {{ hostname }}.{{ domain }}
          ::1       {{ hostname }} {{ hostname }}.{{ domain }}
        dest: /etc/hosts
      register: etc_hosts
    - name: Reload hostname
      ansible.builtin.command: hostname -F /etc/hostname
      when: etc_hosts.changed
    - name: Install containerd, kubelet, kubeadm, kubectl, flannel/CNI stuff
      community.general.apk:
        name:
          - containerd
          - kubelet
          - kubeadm
          - kubectl
          - cni-plugin-flannel
          - cni-plugins
          - flannel
          - flannel-contrib-cni
        update_cache: true
    - name: Enable and start ntpd, containerd
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - ntpd
        - containerd
    - name: Enable kubelet
      ansible.builtin.service:
        name: kubelet
        enabled: true
    - name: Enable net.ipv4.ip_forward
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 1
    - name: Enable net.bridge.bridge-nf-call-iptables
      ansible.posix.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
    - name: Load br_netfilter on reboot
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: "br_netfilter"
        mode: "644"
    - name: Load br_netfilter
      ansible.builtin.modprobe:
        name: br_netfilter
    - name: Load rbd on reboot
      ansible.builtin.copy:
        dest: /etc/modules-load.d/rook.conf
        content: "rbd"
        mode: "644"
    - name: Load rbd
      ansible.builtin.modprobe:
        name: rbd
    - name: Check if /run/udev exists
      ansible.builtin.stat:
        path: /run/udev
      register: udev_check
    - name: Setup udev
      ansible.builtin.command: setup-devd udev
      when: not udev_check.stat.exists

- name: Setup (bootstrap)
  hosts:
    - bootstrap
  tasks:
    - name: Check if cluster exists
      ansible.builtin.shell:
        cmd: kubectl config get-clusters | tail -n +2
      changed_when: false
      register: kubectl_get_clusters
    - name: kubeadm init
      ansible.builtin.shell:
        cmd: kubeadm init --pod-network-cidr=10.244.0.0/16
      when: kubectl_get_clusters.stdout == ""
    - name: Ensure /root/.kube exists
      ansible.builtin.file:
        path: /root/.kube
        state: directory
        mode: "700"
    - name: Create /root/.kube/config link
      ansible.builtin.file:
        path: /root/.kube/config
        src: /etc/kubernetes/admin.conf
        state: link
    - name: Confirm we can get namespaces
      ansible.builtin.command: kubectl get ns
      changed_when: false
    - name: Check if kube-flannel namespace exists
      ansible.builtin.command: kubectl get ns kube-flannel
      register: kube_flannel_ns_check
      failed_when: false
      changed_when: false
    - name: Create kube-flannel namespace
      ansible.builtin.command: kubectl create ns kube-flannel
      when: kube_flannel_ns_check.rc != 0
    - name: Check if flannel stuff applied
      ansible.builtin.shell:
        cmd: kubectl diff -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      register: flannel_diff
      changed_when: false
      failed_when: flannel_diff.rc > 1
    - name: Apply flannel stuff
      ansible.builtin.shell:
        cmd: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      when: flannel_diff.rc == 1

- name: Setup (workers)
  hosts:
    - workers
  tasks:
    - name: Check if node already joined (kubelet kubeconfig exists)
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_kubeconfig
    - name: Get join command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: kubeadm_join
      delegate_to: bootstrap
      when: not kubelet_kubeconfig.stat.exists
    - name: Join cluster
      ansible.builtin.shell:
        cmd: "{{ kubeadm_join.stdout }}"
      when: not kubelet_kubeconfig.stat.exists
